excluded:
  - Pods
  - DrinsedCustomer/SubClasses/KRSCollectionFlowLayout.swift

opt_in_rules:
  - empty_count
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - redundant_nil_coalescing
  - closure_spacing
  - operator_usage_whitespace
  - nimble_operator
  - implicit_return
  - first_where
  - closure_end_indentation
  - sorted_imports
  - strict_fileprivate
  - quick_discouraged_call
  - switch_case_on_newline
  - joined_default_parameter
  - private_outlet
  - multiline_parameters
  - let_var_whitespace
  - attributes
  - conditional_returns_on_newline
  - extension_access_modifier
  - fatal_error_message
  - no_extension_access_modifier
  - force_unwrapping
  - overridden_super_call
  - pattern_matching_keywords
  - single_test_class
  - number_separator
  - multiline_arguments
  - array_init
  - contains_over_first_not_nil
  - literal_expression_end_indentation

disabled_rules:
  - todo
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - block_based_kvo
  - explicit_type_interface
  - trailing_whitespace
  - unused_closure_parameter
  - line_length
  - explicit_init
  - identifier_name
type_body_length:
  - 700
  - 1500
file_length:
  - 800
  - 1600
cyclomatic_complexity:
  - 15
  - 25
line_length:
ignores_comments: true
  - 300
  - 150
function_body_length:
  - 150
  - 250
number_separator:
  minimum_length: 7
  min_length:
    - 1
    - 1
  max_length:
    - 40
    - 40
  excluded:
    - id
    - at
shorthand_operator: error
closure_parameter_position: error
unused_closure_parameter: error
trailing_semicolon: error
trailing_newline: error
syntactic_sugar: error
for_where: error
empty_parentheses_with_trailing_closure: error
opening_brace: error
closing_brace: error
control_statement: error
implicit_getter: error
is_disjoint: error
leading_whitespace: error
#multiple_closures_with_trailing_closure: error
empty_count: error
vertical_parameter_alignment_on_call: error
vertical_parameter_alignment: error
redundant_nil_coalescing: error
closure_spacing: error
operator_usage_whitespace: error
nimble_operator: error
implicit_return: error
first_where: error
closure_end_indentation: error
sorted_imports: error
strict_fileprivate: error
quick_discouraged_call: error
switch_case_on_newline: error
joined_default_parameter: error
multiline_parameters: error
let_var_whitespace: error
#trailing_closure: error
conditional_returns_on_newline: error
fatal_error_message: error
no_extension_access_modifier: error
array_init: error
contains_over_first_not_nil: error
literal_expression_end_indentation: error
unneeded_break_in_switch: error
